language: minimal

services:
  - docker

branches:
  only:
    - main      # cambia a master si tu rama se llama así

jobs:
  include:
    - stage: "Restore"
      name: "Restaurar dependencias NuGet"
      script:
        - echo "== Restaurando dependencias NuGet =="
        - docker run --rm -v "$PWD":/src -w /src
          mcr.microsoft.com/dotnet/sdk:10.0
          dotnet restore TaskManagerApi/TaskManagerApi.csproj

    - stage: "Build"
      name: "Compilar el proyecto"
      script:
        - echo "== Compilando el proyecto =="
        - docker run --rm -v "$PWD":/src -w /src
          mcr.microsoft.com/dotnet/sdk:10.0
          dotnet build TaskManagerApi/TaskManagerApi.csproj -c Release

    - stage: "Test"
      name: "Ejecutar tests"
      script:
        - echo "== Ejecutando tests (si existen) =="
        - docker run --rm -v "$PWD":/src -w /src
          mcr.microsoft.com/dotnet/sdk:10.0
          bash -c "dotnet test || echo 'No hay tests, se omite'"

    - stage: "Docker Build"
      name: "Construir la imagen Docker"
      script:
        - echo "== Construyendo la imagen Docker =="
        - docker build -t productos-api:latest .
 
